"""02 monitor

Revision ID: 582c95e7871b
Revises: cb59c705e266
Create Date: 2025-08-19 21:55:08.831867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '582c95e7871b'
down_revision: Union[str, Sequence[str], None] = 'cb59c705e266'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
   
    op.create_table('monitor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'posting', 'posted', 'failed', name='monitorstatus'), nullable=True),
    sa.Column('payload_client', sa.JSON(), nullable=True),
    sa.Column('payload_sap', sa.JSON(), nullable=True),
    sa.Column('error_details', sa.JSON(), nullable=True),
    sa.Column('sap_doc_entry', sa.Integer(), nullable=True),
    sa.Column('sap_doc_num', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_monitor')),
    schema='mcs'
    )
    op.create_index(op.f('ix_mcs_monitor_sap_doc_entry'), 'monitor', ['sap_doc_entry'], unique=False, schema='mcs')
    op.create_index(op.f('ix_mcs_monitor_sap_doc_num'), 'monitor', ['sap_doc_num'], unique=False, schema='mcs')
    op.create_index(op.f('ix_mcs_monitor_status'), 'monitor', ['status'], unique=False, schema='mcs')
   
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index(op.f('ix_mcs_monitor_status'), table_name='monitor', schema='mcs')
    op.drop_index(op.f('ix_mcs_monitor_sap_doc_num'), table_name='monitor', schema='mcs')
    op.drop_index(op.f('ix_mcs_monitor_sap_doc_entry'), table_name='monitor', schema='mcs')
    op.drop_table('monitor', schema='mcs')
    # ### end Alembic commands ###
